apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
     containers:
       - name: {{ .Chart.Name }}
         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
         imagePullPolicy: {{ .Values.image.pullPolicy }}
         ports:
          {{- toYaml .Values.container.ports | nindent 12 }}
         volumeMounts:
           - name: config
             mountPath: /config
         livenessProbe:
          httpGet:
            path: /actuator/info
            port: http
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5
          successThreshold: 1
         readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5
          successThreshold: 1
     volumes:
       - name: config
         configMap:
           name: configuration-service
